[rule]
id = "rust-no-fixme-comments"
description = "Disallow FIXME comments in Rust code"
severity = "warning"

[match]
language = "rust"
query = """
((line_comment) @violation
 (#match? @violation "(?i)FIXME"))

((block_comment) @violation
 (#match? @violation "(?i)FIXME"))
"""
