[rule]
id = "no-bare-print"
description = "Do not use bare print statements. Use logger.info(), logger.debug() instead"
severity = "warning"

[match]
language = "python"
query = """
(expression_statement
  (call
    function: (identifier) @func
    (#eq? @func "print"))) @violation
"""
